### ISSUE TITLE
create-react-app test compatibility - "Unexpected token 'export'"

### ISSUE THREAD

**Issue by an-aessid** [reactivemarkets/react-financial-charts#488]
#### I'm submitting a...

- [x] bug
- [ ] feature
- [ ] chore

#### What is the current behavior

I am trying to import classes from this library which works when using the app, but when I am running `npm t`, the tests fail with:

```
    /home/xxxxxxxx/git/test/node_modules/react-financial-charts/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from "@react-financial-charts/annotations";
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import logo from './logo.svg';
      2 | import './App.css';
    > 3 | import {
        | ^
      4 |   elderRay
      5 | } from "react-financial-charts";
      6 | function App() {

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1350:14)
      at Object.<anonymous> (src/App.js:3:1)

Test Suites: 1 failed, 1 total
```

#### What is the expected behavior

It should pass.

#### Please tell us about your environment

- Version: 1.1.0
- node version: v15.10.0
- npm version: v7.5.3
- Ubuntu 20.04

#### Other information

I tried different babel and different jest configs (transformIgnorePatterns and such; different things I found when looking for this error), without success.

How to reproduce:

```
npx create-react-app react-financial-charts-test-failure
cd react-financial-charts-test-failure
npm i --save react-financial-charts

// insert any import to App.js
import {elderRay} from "react-financial-charts";
```

and then try `npm t`.

Maybe somebody knows something.

**Comment by an-aessid** [comment]
A good nights sleep works wonders.

This can be solved by adding the following `transformIgnorePatterns` config to a "jest" section in ones package.json.

```
[...]
"jest": {
    "transformIgnorePatterns": [
      "/node_modules/(?!react-financial-charts|@react-financial-charts)"
    ]
  }
```
